sudo: required
dist: trusty

language: node_js

matrix:
  include:
    - os: linux
      node_js: 8.5.0
      
addons:
  artifacts:
     working_dir: packages

before_install:
  - npm install -g yarn

cache: yarn

install:
  - yarn

after_success:
  - yarn run publish:all
