sudo: required
dist: trusty

language: node_js

matrix:
  include:
    - os: linux
      node_js: 8.5.0

addons:
  artifacts: true

addons:
  artifacts:
    debug: true
    paths:
      - ./package
    target_paths: $TRAVIS_BUILD_NUMBER
    bucket: html-importer
    s3_region: 	eu-central-1


before_install:
  - npm install -g yarn

cache: yarn

install:
  - yarn

after_success:
  - yarn run publish:all
